spring:
  application:
    name: J.A.R.V.I.S.
kasa:
  url: https://wap.tplinkcloud.com
  user:
  pass:
  terminal:
  app_type: Kasa_Android
logging:
  level:
    reactor:
      netty:
        http:
          client: DEBUG